server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: device-registry-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projectdemo}
    username: ${SPRING_DATASOURCE_USERNAME:demo}
    password: ${SPRING_DATASOURCE_PASSWORD:demo}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: registry
  flyway:
    enabled: true
    schemas: registry
    default-schema: registry
    create-schemas: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
